name: Test

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create release notes
        run: git log -p -1 CHANGELOG.md
