name: Release

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create release notes
        run: git log -p -n 1 CHANGELOG.md | grep '^+\($\|[^+]\)' | cut -c 2-
